config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root :to => 'artists#index'

  resources :artists do
    resources :music_videos
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user && user.admin?
      can :access, :rails_admin
      can :dashboard
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :music_videos, -> {order(year: :desc)}

  validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  validates :state, presence: true
  validates :region, presence: true
  validates :vibe, presence: true

end

app/models/music_video.rb
class MusicVideo < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  validates :year, presence: true
  validates :link, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.order(:city).includes(:music_videos)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @artists = Artist.order(:name)
    @artist = Artist.new
  end

  def create
    @artists = Artist.order(:name)
    @artist = Artist.new(artist_params)
    if @artist.save
      respond_to do |format|
        format.js { flash.now[:success] = "Artist saved" }
      end
    else
      respond_to do |format|
        format.js { flash.now[:alert] = "Error saving artist" }
      end
    end
  end

  def show
    respond_to do |format|
      format.js { @bio = genius_artist }
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      respond_to do |format|
        format.js { flash.now[:success] = "Artist updated" }
      end
    else
      respond_to do |format|
        format.js { flash.now[:alert] = "Error updating artist" }
      end
    end
  end

  def destroy
    @artist.destroy
    redirect_to new_artist_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :city, :state,:region, :vibe, :genius_id, :bio)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def genius_artist
    if (@artist.genius_id)
      Genius.access_token = 'ejNzHIgJKcQB0SDer4_Astu5ZUx9Sd3N4jZ2m2HYNZLQgtJJVLv4r7xn7r4buQBH'
      @bio = Genius::Artist.find(@artist.genius_id).description
    end
  end
end

app/controllers/music_videos_controller.rb
class MusicVideosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_artist
  before_action :set_music_video, only: [:show, :edit, :update, :destroy]

  def new
    @music_video = @artist.music_videos.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @music_video = @artist.music_videos.new(music_video_params)
    @music_video.youtube_id = YoutubeID.from(@music_video.link)
    if @music_video.save
      respond_to do |format|
        format.js { flash.now[:success] = "Music video saved" }
      end
    else
      respond_to do |format|
        format.js { flash.now[:alert] = "Error saving music video" }
      end
    end
  end

  def show
    @artists = Artist.all
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @music_video.update(music_video_params)
      @music_video.youtube_id = YoutubeID.from(@music_video.link)
      @music_video.save
      respond_to do |format|
        format.js { flash.now[:success] = "Music video updated" }
      end
    else
      respond_to do |format|
        format.js { flash.now[:alert] = "Error updating music video" }
      end
    end
  end

  def destroy
    @music_video.destroy
    redirect_to edit_artist_path(@artist)
  end

  private

  def music_video_params
    params.require(:music_video).permit(:title, :artist_id, :featuring, :featuring_2, :featuring_3, :featuring_4, :year, :link)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_music_video
    @music_video = MusicVideo.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  # def account_update_params
  #   params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/music_videos_helper.rb
module MusicVideosHelper
end

app/views/artists/_artist_links.haml
- @artists.each do |artist|
  .col-xs-3
    = link_to artist.name, artist_path(artist), class: 'artist-link', remote: true

app/views/artists/_artist_panel.html.haml
%h3 Artist Bio
- if @bio
  = @bio
- else
  %p No bio exists for this artist, YET!

app/views/artists/_artist_title.html.haml
.artist-title
  = link_to artist.name, artist_path(artist), class: "white", remote: true

app/views/artists/_edit_form.html.haml
.inline
  %h3 Edit profile
  %br

= simple_form_for(@artist, method: 'patch', remote: true) do |f|
  .form-group
    = f.input :name
  .form-group
    = f.input :city
  .form-group
    = f.input :state
  .form-group
    = f.input :region, :collection => ['east', 'west', 'south', 'midwest', 'global']
  .form-group
    = f.input :vibe, :collection => ['thug','wavy','soul','chill','pop','punk','indie','thump']
  .form-group
    = f.input :genius_id
  .form-group
    = f.input :bio
  .form-group.text-center
    = f.button :submit
%br

app/views/artists/_form.html.haml
%h3 Add new artist
%br

= simple_form_for(@artist, method: 'post', remote: true) do |f|
  .form-group
    = f.input :name
  .form-group
    = f.input :city
  .form-group
    = f.input :state
  .form-group
    = f.input :region, :collection => ['east', 'west', 'south', 'midwest', 'global']
  .form-group
    = f.input :vibe, :collection => ['thug','wavy','soul','chill','pop','punk','word','thump']
  .form-group.text-center
    = f.button :submit
%br

app/views/artists/_preview_videos.html.haml
%h3 Edit videos
%br
- @artist.music_videos.each do |music_video|
  .row
    .col-xs-10
      = link_to music_video.title, edit_artist_music_video_path(@artist, music_video), remote: true
    .col-xs-1
      = link_to "x", artist_music_video_path(@artist, music_video), method: :delete, data: { confirm: 'Are you sure you want to delete "' + music_video.title + '"?' }
  .carousel-tile
    .youtube-player-container
      .youtube-player{ data: {id: music_video.youtube_id } }

app/views/artists/_track_title.html.haml
.track_title
  = music_video.title
  -if !music_video.featuring.empty?
    = ' ft. '
    - if @artists.exists?(name: music_video.featuring)
      - featuring = @artists.find_by(name: music_video.featuring)
      = link_to music_video.featuring, artist_path(featuring), remote: true
    - else
      = music_video.featuring
  -if !music_video.featuring_2.empty?
    = ' // '
    - if @artists.exists?(name: music_video.featuring_2)
      - featuring = @artists.find_by(name: music_video.featuring_2)
      = link_to music_video.featuring_2, artist_path(featuring), remote: true
    - else
      = music_video.featuring_2
  -if !music_video.featuring_3.empty?
    = ' // '
    - if @artists.exists?(name: music_video.featuring_3)
      - featuring = @artists.find_by(name: music_video.featuring_3)
      = link_to music_video.featuring_3, artist_path(featuring), remote: true
    - else
      = music_video.featuring_3
  -if !music_video.featuring_4.empty?
    = ' // '
    - if @artists.exists?(name: music_video.featuring_4)
      - featuring = @artists.find_by(name: music_video.featuring_4)
      = link_to music_video.featuring_4, artist_path(featuring), remote: true
    - else
      = music_video.featuring_4

app/views/artists/create.js.erb
$("#flash-response").html('<%= j render "layouts/flash_response" %>');

$('.artist-links').html('<%= j render "artist_links" %>');

$('#artist_name').val('');
$('#artist_city').val('');
$('#artist_state').val('');
$('#artist_region').val('');
$('#artist_vibe').val('');

app/views/artists/edit.html.haml
.container
  .row
    .col-xs-4
      .artist-form
        = render 'edit_form'
      .edit-artist-form
    .col-xs-4.preview-videos
      = render 'preview_videos'
    .col-xs-4
      .edit-music-video-form
        %br
        %br
        %br
        %br
        %br
        %br
        %h3 Click on track title to edit

app/views/artists/index.js.erb
window.scrollTo( 0, 0)

$('#alphabet-container').hide();
$('#filter-header').show();

app/views/artists/new.html.haml
.container
  .row
    .col-xs-4
      .artist-form
        = render 'new_form'
      .edit-artist-form
      .music-video-form
    .col-xs-8
      .inline
        %h3 Artists
        %h3= button_to '+', new_artist_path(@artist), method: :get, remote: true, id: 'add-new-artist'
      .row
        .col-xs-12.artist-links
          = render 'artist_links'

app/views/artists/new.js.erb
$('.artist-form').html("<%= j render 'new_form' %>");
$('#add-new-artist').hide();

app/views/artists/show.js.erb
$('#artist-panel').html("<%= j render 'artist_panel' %>");

$('.artist-form').html("<%= j render 'artist_detail' %>");
$('#add-new-artist').show();

$('#artist-panel-header').html("<%= @artist.name %>");

app/views/artists/update.js.erb
$("#flash-response").html('<%= j render "layouts/flash_response" %>');

app/views/layouts/_alphabet_links.html.haml
- alphabet = (10...36).map{ |i| i.to_s 36}
- alphabet.each do |char|
  - char.upcase!
  = button_tag char, type: 'button', class: 'alphabet-marker btn-link white', id: "#{char}-marker"
  %br

app/views/layouts/_filters_list.html.haml
.tags
  -# = form_tag(artists_path, method: 'get', remote: true) do
  %h3 play
  #main-playlist-span-container
    %span#main-playlist-span
      = link_to "all young blood", artists_path, id: 'playlist-start', filter: "artist", class: 'main', remote: true
  %h3 or pick playlist
  #vibe-tags
    = link_to "thug", artists_path, id: 'thug-playlist-start', filter: 'thug', class: "vibe", remote: true
    -# = radio_button_tag 'vibe', 'thug', false, vibe: 'thug', class: 'filter filter-radio'
    = link_to "soul", artists_path, id: 'soul-playlist-start',  class: "vibe", filter: 'soul', remote: true
    -# = radio_button_tag 'vibe', 'soul', false, vibe: 'soul', class: 'filter filter-radio'
    = link_to "wavy", artists_path, id: 'wavy-playlist-start', class: "vibe", filter: 'wavy', remote: true
    -# = radio_button_tag 'vibe', 'wavy', false, vibe: 'wavy', class: 'filter filter-radio'
    = link_to "chill", artists_path, id: 'chill-playlist-start', class: "vibe", filter: 'chill', remote: true
    -# = radio_button_tag 'vibe', 'chill', false, vibe: 'chill', class: 'filter filter-radio'
    %br
    = link_to "pop", artists_path, id: 'pop-playlist-start', class: "vibe vibe2", filter: 'pop', remote: true
    -# = radio_button_tag 'vibe', 'pop', false, vibe: 'pop', class: 'filter filter-radio'
    = link_to "punk", artists_path, id: 'punk-playlist-start', class: "vibe vibe2", filter: 'punk', remote: true
    -# = radio_button_tag 'vibe', 'punk', false, vibe: 'punk', class: 'filter filter-radio'
    = link_to "indie", artists_path, id: 'indie-playlist-start', class: "vibe vibe2", filter: 'indie', remote: true
    -# = radio_button_tag 'vibe', 'indie', false, vibe: 'indie', class: 'filter filter-radio'
    = link_to "thump", artists_path, id: 'thump-playlist-start', class: "vibe vibe2", filter: 'thump', remote: true
    -# = radio_button_tag 'vibe', 'thump', false, vibe: 'thump', class: 'filter filter-radio'
  #other-tags
    = link_to "east", artists_path, id: 'east-playlist-start', class: "region", filter: 'east', remote: true
    -# = radio_button_tag 'region', 'east', false, region: 'east', class: 'filter filter-radio'
    = link_to "west", artists_path, id: 'west-playlist-start', class: "region", filter: 'west', remote: true
    -# = radio_button_tag 'region', 'west', false, region: 'west', class: 'filter filter-radio'
    = link_to "south", artists_path, id: 'south-playlist-start', class: "region", filter: 'south', remote: true
    -# = radio_button_tag 'region', 'south', false, region: 'south', class: 'filter filter-radio'
    = link_to "mid", artists_path, id: 'midwest-playlist-start', class: "region", filter: 'midwest', remote: true
    -# = radio_button_tag 'region', 'midwest', false, region: 'midwest', class: 'filter filter-radio'
    = link_to "+", artists_path, id: 'thug-playlist-start', class: "region", filter: 'global', remote: true
    -# = radio_button_tag 'region', 'global', false, region: 'global', class: 'filter filter-radio'
    %br
    = link_to "<-", artists_path, id: 'older-playlist-start', class: "year", filter: 'older', remote: true
    -# = radio_button_tag 'year', '2012', false, year: '2012', class: 'filter filter-radio'
    = link_to "2013", artists_path, id: 'thirteen-playlist-start', class: "year", filter: '2013', remote: true
    -# = radio_button_tag 'year', '2013', false, year: '2013', class: 'filter filter-radio'
    = link_to "2014", artists_path, id: 'fourteen-playlist-start', class: "year", filter: '2014', remote: true
    -# = radio_button_tag 'year', '2014', false, year: '2014', class: 'filter filter-radio'
    = link_to "2015", artists_path, id: 'fifteen-playlist-start', class: "year", filter: '2015', remote: true
    -# = radio_button_tag 'year', '2015', false, year: '2015', class: 'filter filter-radio'
    = link_to "2016", artists_path, id: 'sixteen-playlist-start', class: "year", filter: '2016', remote: true
    -# = radio_button_tag 'year', '2016', false, year: '2016', class: 'filter filter-radio'
  -# .col-xs-2
  -#   = button_tag "ALL", id: 'playlist-start', remote: true

    -# = submit_tag "filter", class: 'submit filter-radio', id: 'advanced-filter-submit'

  -# =button_tag "advanced search", id: 'advanced-toggle'
  -# =button_tag "reset", id: 'reset-radio'

app/views/layouts/_flash_response.html.haml
-flash.each do |name, msg|
  = content_tag :div, msg, class: [:alert, alert_for(name)]

app/views/layouts/_navbar.html.haml
-# %nav.navbar.navbar-default.navbar-fixed-top#my-nav
-#   .navbar-container.row
-#     .navbar-brand.col-xs-2
-#       = link_to image_tag("young_blood_nav.png"), root_path, class: "logo-nav"
-#     .col-xs-6.pull-right.filters
-#       = render 'layouts/filters_list'
-#     .nav-account.navbar-left.col-xs-2
-#       - if user_signed_in?
-#         = link_to "submit", new_artist_path
-#         = link_to "logout", destroy_user_session_path, method: :delete
-#       - else
-#         = link_to "login", new_user_session_path
-#         = link_to "join", new_user_registration_path

app/views/layouts/application.html.haml
%html
  %head
    %title Young Blood
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}

    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Bungee|Nova+Mono"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags


  %body
    -# #landing_page
    -#   = image_tag "young_blood_logo_white_text.png"
    -# %script(type='text/javascript')
      -# $("#landing_page").show().delay(800).slideUp(1000).delay(400);
    #header_container
      #young_blood_header
        = render 'layouts/navbar'
      #alphabet-container.text-center
        = render 'layouts/alphabet_links'
    #content-container
      #flash-response
        = render 'layouts/flash_response'
      = yield
    -# %script(type='text/javascript')
      -# $("#young_blood_header").delay(1600).fadeIn(800);
      -# $("#content-container").delay(2600).show();

app/views/music_videos/_edit_form.html.haml
.inline
  %h3 Edit "
  %h3= @music_video.title
  %h3 "
%br

= simple_form_for([@artist, @music_video], method: 'patch', remote: true) do |f|
  .form-group
    = f.input :title
  .form-group
    = f.input :year
  .form-group
    = f.input :link
  .row
    .form-group.col-xs-10
      = f.input :featuring
    .form-group.col-xs-10#ft-2
      = f.input :featuring_2
    .form-group.col-xs-10#ft-3
      = f.input :featuring_3
    .form-group.col-xs-10#ft-4
      = f.input :featuring_4
    = button_tag "+", type: 'button', id: 'plus-feature'
  .form-group.text-center
    = f.button :submit

app/views/music_videos/_form.html.haml
= simple_form_for([@artist, @music_video], method: 'post', remote: true) do |f|
  .form-group
    = f.input :title
  .row
    .form-group.col-xs-3
      = f.input :featuring
    .form-group.col-xs-3
      = f.input :featuring_2
    .form-group.col-xs-3
      = f.input :featuring_3
    .form-group.col-xs-3
      = f.input :featuring_4
  .form-group
    = f.input :year
  .form-group
    = f.input :link
  .form-group.text-center
    = f.button :submit

app/views/music_videos/_new_form.html.haml
%h3 Add new video
%br

= simple_form_for([@artist, @music_video], method: 'post', remote: true) do |f|
  .form-group
    = f.input :title
  .form-group
    = f.input :year
  .form-group
    = f.input :link
  .row
    .form-group.col-xs-10
      = f.input :featuring
    .form-group.col-xs-10#ft-2
      = f.input :featuring_2
    .form-group.col-xs-10#ft-3
      = f.input :featuring_3
    .form-group.col-xs-10#ft-4
      = f.input :featuring_4
    = button_tag "+", type: 'button', id: 'plus-feature'
  .form-group.text-center
    = f.button :submit

app/views/music_videos/_now_playing.html.haml
%h3.gold Now Playing
-# = button_tag '', type: 'button', class: "btn", id: 'play-next-btn', remote: true

= render 'artists/track_title', music_video: @music_video
by
= @music_video.artist.name

app/views/music_videos/create.js.erb
$("#flash-response").html('<%= j render "layouts/flash_response" %>');

$('#music_video_title').val('');
$('#music_video_featuring').val('');
$('#music_video_featuring_2').val('');
$('#music_video_featuring_3').val('');
$('#music_video_featuring_4').val('');
$('#music_video_year').val('');
$('#music_video_link').val('');

app/views/music_videos/edit.js.erb
$('.edit-music-video-form').html("<%= j render 'edit_form' %>");

var ft_counter = 2;
$('#plus-feature').on('click', function() {
  $('#ft-' + ft_counter.toString()).show();
  ft_counter += 1;
});

app/views/music_videos/new.js.erb
$('.new-music-video-form').html("<%= j render 'new_form' %>");

var ft_counter = 2;
$('#plus-feature').on('click', function() {
  $('#ft-' + ft_counter.toString()).show();
  ft_counter += 1;
});

app/views/music_videos/show.js.erb
$('#now-playing').html("<%= j render 'now_playing' %>");

app/views/music_videos/update.js.erb
$("#flash-response").html('<%= j render "layouts/flash_response" %>');

$(".preview-videos").html('<%= j render "artists/preview_videos" %>');

var div, n,
v = document.getElementsByClassName("youtube-player");
for (n = 0; n < v.length; n++) {
  div = document.createElement("div");
  div.setAttribute("data-id", v[n].dataset.id);
  div.innerHTML = labnolThumb(v[n].dataset.id);
  div.onclick = labnolIframe;
  v[n].appendChild(div);
}